<?php

namespace Admin\Controller;

use App\Controller\AppController as BaseController;
use Cake\Core\Configure;
use Cake\Event\Event;

/**
 * @property bool|object Menus
 * @property bool layout
 */
class AppController extends BaseController
{
    public $imageFields = [];

    public $filterEquals = ['status', 'group'];

    public function initialize()
    {
        parent::initialize();
    }

    public function index()
    {
        $model = $this->modelClass;
        $model = str_replace('Admin.', '', $model);
        $searchFields = $this->request->query('S');
        $conditions = $searchFillFormData = [];
        if ($searchFields) {
            foreach ($searchFields as $field => $value) {
                $searchFillFormData['S['.$field.']'] = $value;
                if ($value == null) {
                    continue;
                }
                if (strpos($field, '*')) {
                    $fieldSearch = str_replace('*', '.', $field);
                } else {
                    $fieldSearch = $model.'.'.$field;
                }

                if (in_array($field, $this->filterEquals)) {
                    $conditions[$fieldSearch] = $value;
                } else {
                    $conditions[$fieldSearch.' LIKE'] = '%'.$value.'%';
                }
            }
        }
        $this->paginate['conditions'] = $conditions;
        $this->request->data = $searchFillFormData;
    }

    /**
     * @param Event $event
     */
    public function beforeRender(Event $event)
    {
        //$this->set('imageFields', $this->imageFields);
        parent::beforeRender($event); // TODO: Change the autogenerated stub
    }
}
