<?php
namespace Admin\Controller;

use Admin\Controller\AppController;

/**
 * Fashions Controller
 *
 * @property \Admin\Model\Table\FashionsTable $Fashions
 */
class FashionsController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadModel('Slides');
    }

    /**
     * Index method
     *
     * @return \Cake\Network\Response|null
     */
    public function index()
    {
        $hello = $this->Fashions->find('all')->contain('Slides');
        debug($hello);die;
        $fashions = $this->paginate($this->Fashions);

        $this->set(compact('fashions'));
        $this->set('_serialize', ['fashions']);
    }

    /**
     * View method
     *
     * @param string|null $id Busines id.
     * @return \Cake\Network\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $fashion = $this->Fashions->get($id, [
            'contain' => []
        ]);

        $this->set('fashion', $fashion);
        $this->set('_serialize', ['$business']);
    }

    /**
     * Add method
     *
     * @return \Cake\Network\Response|void Redirects on successful add, renders view otherwise.
     */
    public function form($id = null)
    {

        $fashion = $this->Fashions->newEntity();
        if($id){
            $fashion = $this->Fashions->get($id);
//            debug($fashion);die;
        }

        if ($this->request->data) {
            $fashion = $this->Core->patchEntity($fashion, $this->request->data);
            if ($this->Fashions->save($fashion)) {
                $this->Flash->success(__('The Fashions has been saved.'));

                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('The Fashions could not be saved. Please, try again.'));
            }
        }
        $this->set(compact('fashion'));
        $this->set('_serialize', ['fashion']);
    }

    /**
     * Edit method
     *
     * @param string|null $id Busines id.
     * @return \Cake\Network\Response|void Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */

    /**
     * Delete method
     *
     * @param string|null $id Busines id.
     * @return \Cake\Network\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $fashions = $this->Fashions->get($id);
//        debug($business);die;
        if ($this->Fashions->delete($fashions)) {
            $this->Flash->success(__('The business has been deleted.'));
        } else {
            $this->Flash->error(__('The business could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }
}
